AWSTemplateFormatVersion: '2010-09-09'
Description: mulperiCMS AWS infra
Parameters:
  StackName:
    Type: String
Resources:
  DynamoDBCommentsTable:
    DependsOn: DynamoDBPostsTable
    Description: Table for comments, need postId for reference
    Properties:
      AttributeDefinitions:
      - AttributeName: id
        AttributeType: S
      - AttributeName: postId
        AttributeType: S
      GlobalSecondaryIndexes:
      - IndexName: postId
        KeySchema:
        - AttributeName: postId
          KeyType: HASH
        Projection:
          ProjectionType: ALL
        ReadCapacityUnits: '1'
        WriteCapacityUnits: '1'
      KeySchema:
      - AttributeName: id
        KeyType: HASH
      - AttributeName: postId
        KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: '5'
        WriteCapacityUnits: '5'
      TableName:
        Fn::Sub: ${StackName}-comments
    Type: AWS::DynamoDB::Table
  DynamoDBPostsTable:
    Description: Table for posts
    Properties:
      AttributeDefinitions:
      - AttributeName: id
        AttributeType: S
      KeySchema:
      - AttributeName: id
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: '5'
        WriteCapacityUnits: '5'
      TableName:
        Fn::Sub: ${StackName}-posts
    Type: AWS::DynamoDB::Table
  UserPool:
    Description: A Cognito user pool for authenticating users
    Properties:
      AliasAttributes:
      - email
      - preferred_username
      AutoVerifiedAttributes:
      - email
      EmailVerificationMessage: 'mulperiCMS confirmation code: {####}'
      EmailVerificationSubject: mulperiCMS confirmation code
      Schema:
      - Mutable: false
        Name: email
        Required: true
      UserPoolName:
        Fn::Sub: ${StackName}-users
    Type: AWS::Cognito::UserPool
  UserPoolClient:
    DependsOn: UserPool
    Description: A Cognito app client for Angular
    Properties:
      ClientName:
        Fn::Sub: ${StackName}-angular
      GenerateSecret: false
      UserPoolId:
        Ref: UserPool
    Type: AWS::Cognito::UserPoolClient
